#!/usr/bin/env node
// npm create brahma-xr my-project → a minimal, ready-to-run shared virtual
// world: World.js + sources.js + entry files, with the Experience wiring
// living in the brahma-xr library. No prompts, no dependencies.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = path.dirname(fileURLToPath(import.meta.url));

const targetArg = process.argv[2];
if (!targetArg || targetArg.startsWith("-")) {
  console.log(`Usage:
  npm create brahma-xr@latest <project-directory>

Example:
  npm create brahma-xr@latest my-world`);
  process.exit(targetArg ? 0 : 1);
}

const targetDir = path.resolve(process.cwd(), targetArg);
if (fs.existsSync(targetDir) && fs.readdirSync(targetDir).length > 0) {
  console.error(`✖ ${targetArg} already exists and is not empty`);
  process.exit(1);
}

// Published tarballs carry template/ (generated by prepack); in a monorepo
// checkout it may not exist yet — sync it from starter/ on the fly.
let templateDir = path.join(pkgDir, "template");
if (!fs.existsSync(templateDir)) {
  const { syncTemplate } = await import("./sync-template.mjs");
  templateDir = syncTemplate();
}

const projectName = path
  .basename(targetDir)
  .toLowerCase()
  .replace(/[^a-z0-9-_.~]+/g, "-")
  .replace(/^[-.]+|-+$/g, "");

fs.cpSync(templateDir, targetDir, { recursive: true });
fs.renameSync(
  path.join(targetDir, "gitignore"),
  path.join(targetDir, ".gitignore"),
);

const pkgPath = path.join(targetDir, "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
pkg.name = projectName || "my-brahma-world";
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");

const cd = path.relative(process.cwd(), targetDir);
console.log(`
✔ Created ${pkg.name}

  cd ${cd}
  npm install
  npm run dev            # the app — https://localhost:5173
  npx brahma-xr-server   # the relay, in a second terminal

Open https://localhost:5173 in two tabs and click Join Session in both —
that's multiplayer. Edit src/Experience/World.js to build your world.
Headsets, deploys (npm run build → docs/): see README.md.
`);
